# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\smoke_detector.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_stop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.lbl_info = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info.setObjectName("lbl_info")
        self.horizontalLayout.addWidget(self.lbl_info)
        self.gridLayout_9.addLayout(self.horizontalLayout, 4, 0, 1, 7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lbl_ip3 = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_ip3.setObjectName("lbl_ip3")
        self.gridLayout_8.addWidget(self.lbl_ip3, 1, 1, 1, 1)
        self.lbl_t3 = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_t3.setObjectName("lbl_t3")
        self.gridLayout_8.addWidget(self.lbl_t3, 0, 1, 1, 1)
        self.gview_3 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.gview_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_3.setObjectName("gview_3")
        self.gridLayout_8.addWidget(self.gview_3, 0, 0, 2, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 0, 4, 2, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_t1 = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_t1.setObjectName("lbl_t1")
        self.gridLayout_7.addWidget(self.lbl_t1, 0, 2, 1, 1)
        self.gview_1 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.gview_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_1.setObjectName("gview_1")
        self.gridLayout_7.addWidget(self.gview_1, 0, 1, 2, 1)
        self.lbl_ip1 = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_ip1.setObjectName("lbl_ip1")
        self.gridLayout_7.addWidget(self.lbl_ip1, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 0, 0, 2, 2)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_ip2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_ip2.setObjectName("lbl_ip2")
        self.gridLayout_4.addWidget(self.lbl_ip2, 1, 1, 1, 1)
        self.gview_2 = QtWidgets.QGraphicsView(self.groupBox)
        self.gview_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gview_2.setObjectName("gview_2")
        self.gridLayout_4.addWidget(self.gview_2, 0, 0, 2, 1)
        self.lbl_t2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_t2.setObjectName("lbl_t2")
        self.gridLayout_4.addWidget(self.lbl_t2, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 2, 2, 2)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuStart = QtWidgets.QMenu(self.menubar)
        self.menuStart.setObjectName("menuStart")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuHilfe.setFont(font)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVerbinden = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionVerbinden.setFont(font)
        self.actionVerbinden.setObjectName("actionVerbinden")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionBeenden.setFont(font)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuStart.addAction(self.actionVerbinden)
        self.menuStart.addSeparator()
        self.menuStart.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionInfo)
        self.menubar.addAction(self.menuStart.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smarte Rauchmelder über Ethernet"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rauchmelder"))
        self.btn_stop.setText(_translate("MainWindow", "Stop Alarm"))
        self.lbl_info.setText(_translate("MainWindow", "Alles Ok"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Garage"))
        self.lbl_ip3.setText(_translate("MainWindow", "000.000.000.000"))
        self.lbl_t3.setText(_translate("MainWindow", "00.00 °C"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dachboden Büro"))
        self.lbl_t1.setText(_translate("MainWindow", "00.00 °C"))
        self.lbl_ip1.setText(_translate("MainWindow", "000.000.000.000"))
        self.groupBox.setTitle(_translate("MainWindow", "Dachboden Werkstatt"))
        self.lbl_ip2.setText(_translate("MainWindow", "000.000.000.000"))
        self.lbl_t2.setText(_translate("MainWindow", "00.00 °C"))
        self.menuStart.setTitle(_translate("MainWindow", "Start"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.actionVerbinden.setText(_translate("MainWindow", "Verbinden"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))

